server:
  port: 8081
spring:
  application:
    name: employee-management-system
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/employee_management_app
    username: techguy
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true